=== mupuf/diaforus_labri/diaforus/scenarios/network.dtd
<!ELEMENT network (build, coap_groups?, node*) >
<!ELEMENT build (make*, debug, application) >
<!ELEMENT make EMPTY >
<!ELEMENT debug EMPTY >
<!ELEMENT application EMPTY >

<!ELEMENT node ((emblem)?, firmware, phy, energy, (rpl)?, pubsub, coap, (gateway)?, (reasoning)?, (parameter*), sensors) >

<!ELEMENT emblem EMPTY >
<!ELEMENT firmware EMPTY >
<!ELEMENT phy EMPTY >
<!ELEMENT energy EMPTY >
<!ELEMENT rpl (restrict_neighbors)? >
<!ELEMENT pubsub EMPTY >
<!ELEMENT coap_groups (group*) >
<!ELEMENT coap (group*) >
<!ELEMENT group (resource*)? >
<!ELEMENT resource EMPTY>
<!ELEMENT gateway EMPTY >
<!ELEMENT parameter EMPTY >
<!ELEMENT sensors (modality*) >

<!ELEMENT restrict_neighbors (neighbor*) >
<!ELEMENT neighbor EMPTY >

<!ELEMENT modality (sensor*) >

<!ELEMENT sensor ((i2c|gpio|adc), value, position) >

<!ELEMENT i2c EMPTY >
<!ELEMENT gpio EMPTY >
<!ELEMENT adc EMPTY >
<!ELEMENT value EMPTY >
<!ELEMENT position EMPTY >
<!ELEMENT reasoning ((reasoning_node)?, (monitored_area)?) >
<!ELEMENT monitored_area EMPTY >
<!ELEMENT reasoning_node EMPTY >

<!ATTLIST emblem source CDATA #REQUIRED>
<!ATTLIST group name CDATA #REQUIRED>
<!ATTLIST resource name CDATA #REQUIRED>
<!ATTLIST network pubsub_reliable (true|false) #REQUIRED failure_handling (true|false) #REQUIRED>

<!ATTLIST reasoning min_intrusion_duration CDATA #REQUIRED max_intrusion_duration CDATA #REQUIRED latency_mode (white|green|yellow|orange|red) #REQUIRED >
<!ATTLIST reasoning_node log_analyse_period CDATA #REQUIRED >
<!ATTLIST monitored_area average_crossing_duration CDATA #REQUIRED >
<!ATTLIST monitored_area area CDATA #REQUIRED >

<!ATTLIST make path CDATA #IMPLIED args CDATA #IMPLIED root CDATA #REQUIRED output CDATA #REQUIRED target (host|aps3) #REQUIRED >
<!ATTLIST debug wavesim (true|false) #IMPLIED uip (true|false) #IMPLIED sicslowpan (true|false) #IMPLIED rpl (true|false) #IMPLIED pubsub (true|false) #REQUIRED coap (true|false) #REQUIRED reasoning (true|false) #REQUIRED >
<!ATTLIST application name CDATA #REQUIRED >

<!ATTLIST node id CDATA #REQUIRED area CDATA #REQUIRED name CDATA #IMPLIED target (host|aps3) #REQUIRED simulation (true|false) #REQUIRED >

<!ATTLIST firmware name CDATA #REQUIRED >
<!ATTLIST phy x CDATA #REQUIRED y CDATA #REQUIRED range CDATA #REQUIRED>
<!ATTLIST energy startup CDATA #REQUIRED alarm CDATA #REQUIRED >
<!ATTLIST rpl prefix CDATA #IMPLIED root (true|false) #IMPLIED >
<!ATTLIST pubsub enable (true|false) #REQUIRED broker (true|false) #IMPLIED>
<!ATTLIST coap enable (true|false) #REQUIRED>
<!ATTLIST gateway port CDATA #REQUIRED>
<!ATTLIST parameter type (string|other) #IMPLIED name CDATA #REQUIRED value CDATA #IMPLIED>

<!ATTLIST neighbor node_id CDATA #REQUIRED>

<!ATTLIST sensors>

<!ATTLIST modality type (PIR|SPIRIT|SEISMIC|SWITCH) #REQUIRED >

<!ATTLIST sensor id CDATA #REQUIRED type (digital|analog) #REQUIRED period CDATA #REQUIRED delay CDATA #IMPLIED reemission_delay CDATA #IMPLIED>

<!ATTLIST i2c address CDATA #REQUIRED register CDATA #REQUIRED >
<!ATTLIST adc pin CDATA #REQUIRED >
<!ATTLIST gpio pin CDATA #REQUIRED >
<!ATTLIST value invert (true|false) #IMPLIED offset CDATA #IMPLIED mult CDATA #IMPLIED div CDATA #IMPLIED abs_threshold CDATA #REQUIRED rel_threshold CDATA #REQUIRED>
<!ATTLIST position x CDATA #REQUIRED y CDATA #REQUIRED z_rotation CDATA #REQUIRED>

=== mupuf/diaforus_labri/diaforus/scenarios/ferte/ferte_resilience_net_simu.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE network SYSTEM '../network.dtd'>
<network failure_handling="true" pubsub_reliable="true">
    <build>
        <!--	path: filepath to the make binary (optional)
			args: parameters you can specify for make (optional)
			root: the directory that contains the Makefile
			output: the binary file generated by the project
		-->
        <make output="diaforus_final_code" root="build/" target="host" args="-j8"/>
        <make output="diaforus_final_code.jtag.s3" root="Debug/" target="aps3" args="-j1"/>
        <debug pubsub="true" uip="false" sicslowpan="false" rpl="false" wavesim="false" coap="true" reasoning="true"/>
        <application name="REASONING"/>
    </build>
    <coap_groups>
        <group name="reasoning1">
            <resource name="intrusion_duration"/>
            <resource name="latency_mode"/>
        </group>
        <group name="reasoning2">
            <resource name="hist_analyze_per"/>
            <resource name="criticality_lvl"/>
            <resource name="history"/>
            <resource name="alert_alarm_ratio"/>
        </group>
        <group name="rpl">
            <resource name="rpl_neighbors"/>
            <resource name="rpl_rank"/>
            <resource name="rpl_num_routes"/>
            <resource name="rpl_num_tra_mess"/>
            <resource name="rpl_num_rec_mess"/>
        </group>
        <group name="allnodes">
            <resource name="num_tra_packets"/>
            <resource name="num_rec_packets"/>
            <resource name="nodeid"/>
        </group>
    </coap_groups>
    <!-- Zone 2 -->
    <node target="host" simulation="true" id="1" area="2" name="node root broker">
        <emblem source="c2.png"/>
        <firmware name="node_1"/>
         <phy x="1100" y="937" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl prefix="1180:0000:0000:0000">
            <restrict_neighbors>
                <neighbor node_id="2"/>
                <neighbor node_id="7"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true" broker="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <gateway port="1235"/>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="white" max_intrusion_duration="5" min_intrusion_duration="2"/>
        <parameter value="1" name="INDOOR_SCENARIO"/>
        <sensors/>
    </node>
    <node target="host" simulation="true" id="7" area="2" name="node reasoning 2">
        <firmware name="node_7"/>
        <phy x="1200" y="746" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
				<neighbor node_id="2"/>
				<neighbor node_id="3"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="white" max_intrusion_duration="5" min_intrusion_duration="2">
            <!-- This node is the reasoning node -->
            <reasoning_node log_analyse_period="1440"/>
            <!-- in minutes -->
            <monitored_area area="1" average_crossing_duration="10"/>
        </reasoning>
        <parameter value="1" name="INDOOR_SCENARIO"/>
        <sensors/>
    </node>
    <node target="host" simulation="true" id="2" area="2" name="node pir 3">
        <firmware name="node_2"/>
        <phy x="1058" y="746" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
				<neighbor node_id="3"/>
				<neighbor node_id="7"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="5" min_intrusion_duration="2"/>
        <parameter value="1" name="INDOOR_SCENARIO"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="996" y="770" z_rotation="180"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="3" area="2" name="node spirit">
        <firmware name="node_3"/>
        <phy x="1000" y="515" range="400"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="2"/>
                <neighbor node_id="7"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="5" min_intrusion_duration="2"/>
        <parameter value="1" name="INDOOR_SCENARIO"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="920" y="542" z_rotation="160"/>
                </sensor>
            </modality>
        </sensors>
    </node>
</network>
