=== mupuf/diaforus_labri/diaforus/scenarios/network.dtd
<!ELEMENT network (build, coap_groups?, node*) >
<!ELEMENT build (make*, debug, application) >
<!ELEMENT make EMPTY >
<!ELEMENT debug EMPTY >
<!ELEMENT application EMPTY >

<!ELEMENT node ((emblem)?, firmware, phy, energy, (rpl)?, pubsub, coap, (gateway)?, (reasoning)?, (parameter*), sensors) >

<!ELEMENT emblem EMPTY >
<!ELEMENT firmware EMPTY >
<!ELEMENT phy EMPTY >
<!ELEMENT energy EMPTY >
<!ELEMENT rpl (restrict_neighbors)? >
<!ELEMENT pubsub EMPTY >
<!ELEMENT coap_groups (group*) >
<!ELEMENT coap (group*) >
<!ELEMENT group (resource*)? >
<!ELEMENT resource EMPTY>
<!ELEMENT gateway EMPTY >
<!ELEMENT parameter EMPTY >
<!ELEMENT sensors (modality*) >

<!ELEMENT restrict_neighbors (neighbor*) >
<!ELEMENT neighbor EMPTY >

<!ELEMENT modality (sensor*) >

<!ELEMENT sensor ((i2c|gpio|adc), value, position) >

<!ELEMENT i2c EMPTY >
<!ELEMENT gpio EMPTY >
<!ELEMENT adc EMPTY >
<!ELEMENT value EMPTY >
<!ELEMENT position EMPTY >
<!ELEMENT reasoning ((reasoning_node)?, (monitored_area)?) >
<!ELEMENT monitored_area EMPTY >
<!ELEMENT reasoning_node EMPTY >

<!ATTLIST emblem source CDATA #REQUIRED>
<!ATTLIST group name CDATA #REQUIRED>
<!ATTLIST resource name CDATA #REQUIRED>
<!ATTLIST network pubsub_reliable (true|false) #REQUIRED failure_handling (true|false) #REQUIRED>

<!ATTLIST reasoning min_intrusion_duration CDATA #REQUIRED max_intrusion_duration CDATA #REQUIRED latency_mode (white|green|yellow|orange|red) #REQUIRED >
<!ATTLIST reasoning_node log_analyse_period CDATA #REQUIRED >
<!ATTLIST monitored_area average_crossing_duration CDATA #REQUIRED >
<!ATTLIST monitored_area area CDATA #REQUIRED >

<!ATTLIST make path CDATA #IMPLIED args CDATA #IMPLIED root CDATA #REQUIRED output CDATA #REQUIRED target (host|aps3) #REQUIRED >
<!ATTLIST debug wavesim (true|false) #IMPLIED uip (true|false) #IMPLIED sicslowpan (true|false) #IMPLIED rpl (true|false) #IMPLIED pubsub (true|false) #REQUIRED coap (true|false) #REQUIRED reasoning (true|false) #REQUIRED >
<!ATTLIST application name CDATA #REQUIRED >

<!ATTLIST node id CDATA #REQUIRED area CDATA #REQUIRED name CDATA #IMPLIED target (host|aps3) #REQUIRED simulation (true|false) #REQUIRED >

<!ATTLIST firmware name CDATA #REQUIRED >
<!ATTLIST phy x CDATA #REQUIRED y CDATA #REQUIRED range CDATA #REQUIRED>
<!ATTLIST energy startup CDATA #REQUIRED alarm CDATA #REQUIRED >
<!ATTLIST rpl prefix CDATA #IMPLIED root (true|false) #IMPLIED >
<!ATTLIST pubsub enable (true|false) #REQUIRED broker (true|false) #IMPLIED>
<!ATTLIST coap enable (true|false) #REQUIRED>
<!ATTLIST gateway port CDATA #REQUIRED>
<!ATTLIST parameter type (string|other) #IMPLIED name CDATA #REQUIRED value CDATA #IMPLIED>

<!ATTLIST neighbor node_id CDATA #REQUIRED>

<!ATTLIST sensors>

<!ATTLIST modality type (PIR|SPIRIT|SEISMIC|SWITCH) #REQUIRED >

<!ATTLIST sensor id CDATA #REQUIRED type (digital|analog) #REQUIRED period CDATA #REQUIRED delay CDATA #IMPLIED reemission_delay CDATA #IMPLIED>

<!ATTLIST i2c address CDATA #REQUIRED register CDATA #REQUIRED >
<!ATTLIST adc pin CDATA #REQUIRED >
<!ATTLIST gpio pin CDATA #REQUIRED >
<!ATTLIST value invert (true|false) #IMPLIED offset CDATA #IMPLIED mult CDATA #IMPLIED div CDATA #IMPLIED abs_threshold CDATA #REQUIRED rel_threshold CDATA #REQUIRED>
<!ATTLIST position x CDATA #REQUIRED y CDATA #REQUIRED z_rotation CDATA #REQUIRED>

=== mupuf/diaforus_labri/diaforus/scenarios/ferte/ferte_niveaux_couleurs.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE network SYSTEM '../network.dtd'>
<network failure_handling="false" pubsub_reliable="true">
    <build>
        <!--	path: filepath to the make binary (optional)
			args: parameters you can specify for make (optional)
			root: the directory that contains the Makefile
			output: the binary file generated by the project
		-->
        <make output="diaforus_final_code" root="build/" target="host" args="-j8"/>
        <debug pubsub="true" uip="false" sicslowpan="false" rpl="false" wavesim="false" coap="false" reasoning="true"/>
        <application name="REASONING"/>
    </build>
    <coap_groups>
        <group name="reasoning1">
            <resource name="intrusion_duration"/>
            <resource name="latency_mode"/>
        </group>
        <group name="reasoning2">
            <resource name="hist_analyze_per"/>
            <resource name="criticality_lvl"/>
            <resource name="history"/>
            <resource name="alert_alarm_ratio"/>
        </group>
        <group name="rpl">
            <resource name="rpl_neighbors"/>
            <resource name="rpl_rank"/>
            <resource name="rpl_num_routes"/>
            <resource name="rpl_num_tra_mess"/>
            <resource name="rpl_num_rec_mess"/>
        </group>
        <group name="allnodes">
            <resource name="num_tra_packets"/>
            <resource name="num_rec_packets"/>
            <resource name="nodeid"/>
        </group>
    </coap_groups>
    <!-- Zone 1 -->
    <node target="host" simulation="true" id="20" area="1" name="node root reasoning 1">
        <firmware name="node_20"/>
        <phy x="910" y="865" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2">
            <!-- This node is the reasoning node -->
            <reasoning_node log_analyse_period="1440"/>
        </reasoning>
        <sensors/>
    </node>
    <node target="host" simulation="true" id="2" area="1" name="node pir 2-1">
        <firmware name="node_2"/>
        <phy x="786" y="856" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="738" y="798" z_rotation="-110"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="5" area="1" name="node pir 2-1">
        <firmware name="node_5"/>
        <phy x="846" y="743" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <sensors>
            <modality type="SEISMIC">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="819" y="719" z_rotation="155"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="3" area="1" name="node pir 3-1">
        <firmware name="node_3"/>
        <phy x="956" y="799" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="905" y="738" z_rotation="-110"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <!-- Zone 2-->
    <node target="host" simulation="true" id="1" area="2" name="gateway">
        <emblem source="c2.png"/>
        <firmware name="node_1"/>
        <phy x="1138" y="863" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl prefix="1180:0000:0000:0000"/>
        <pubsub enable="true" broker="true"/>
        <coap enable="true">
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <gateway port="1235"/>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <sensors/>
    </node>
    <node target="host" simulation="true" id="21" area="2" name="node pir 1-2">
        <firmware name="node_21"/>
        <phy x="1174" y="632" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <sensors>
            <modality type="SEISMIC">
                <sensor period="200" reemission_delay="5001" type="digital" id="0" delay="0">
                    <gpio pin="3"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="1121" y="614" z_rotation="80"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="22" area="2" name="node pir 2-2">
        <firmware name="node_22"/>
        <phy x="1350" y="585" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <parameter value="WITH_SPIRIT" name="HW_MODALITY"/>
        <parameter value="-240" name="M_FREQ_OFFSET"/>
        <sensors>
            <modality type="SPIRIT">
                <sensor period="100" reemission_delay="1001" type="digital" id="0" delay="0">
                    <gpio pin="0"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="1354" y="561" z_rotation="0"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="23" area="2" name="node pir 2-2">
        <firmware name="node_23"/>
        <phy x="1289" y="680" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2"/>
        <parameter value="WITH_SPIRIT" name="HW_MODALITY"/>
        <parameter value="-96" name="M_FREQ_OFFSET"/>
        <sensors>
            <modality type="SEISMIC">
                <sensor period="500" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="0"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="1244" y="590" z_rotation="190"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="4" area="2" name="node buzzer 4">
        <emblem source="buzzer.png"/>
        <firmware name="node_4"/>
        <phy x="1374" y="687" range="900"/>
        <energy startup="1600" alarm="100"/>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="20" min_intrusion_duration="2">
            <!-- This node is the reasoning node -->
            <reasoning_node log_analyse_period="1440"/>
            <!-- in minutes -->
            <!-- <monitored_area area="1" average_crossing_duration="20"/> -->
        </reasoning>
        <parameter value="NO_DEMOBOARD" name="HW_MODALITY"/>
        <parameter value="-96" name="M_FREQ_OFFSET"/>
        <sensors/>
    </node>
</network>

=== mupuf/diaforus_labri/diaforus/scenarios/ferte/ferte_adjacence_et_niveaux_network.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE network SYSTEM '../network.dtd'>
<network failure_handling="false" pubsub_reliable="true">
    <build>
        <!--	path: filepath to the make binary (optional)
			args: parameters you can specify for make (optional)
			root: the directory that contains the Makefile
			output: the binary file generated by the project
		-->
        <make output="diaforus_final_code" root="build/" target="host" args="-j8"/>
        <make output="diaforus_final_code.jtag.s3" root="Debug/" target="aps3" args="-j1"/>
        <debug pubsub="true" uip="false" sicslowpan="false" rpl="false" wavesim="false" coap="false" reasoning="true"/>
        <application name="REASONING"/>
    </build>
    <coap_groups>
        <group name="reasoning1">
            <resource name="intrusion_duration"/>
            <resource name="latency_mode"/>
        </group>
        <group name="reasoning2">
            <resource name="hist_analyze_per"/>
            <resource name="criticality_lvl"/>
            <resource name="history"/>
            <resource name="alert_alarm_ratio"/>
        </group>
        <group name="rpl">
            <resource name="rpl_neighbors"/>
            <resource name="rpl_rank"/>
            <resource name="rpl_num_routes"/>
            <resource name="rpl_num_tra_mess"/>
            <resource name="rpl_num_rec_mess"/>
        </group>
        <group name="allnodes">
            <resource name="num_tra_packets"/>
            <resource name="num_rec_packets"/>
            <resource name="nodeid"/>
        </group>
    </coap_groups>
    <!-- Zone 1 -->
    <node target="host" simulation="true" id="20" area="1" name="node root reasoning 1">
        <firmware name="node_20"/>
        <phy x="837" y="675" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
                <neighbor node_id="2"/>
                <neighbor node_id="3"/>
                <neighbor node_id="4"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5">
            <!-- This node is the reasoning node -->
            <reasoning_node log_analyse_period="1440"/>
        </reasoning>
        <sensors/>
    </node>
    <node target="aps3" simulation="false" id="9" area="1" name="node pir 9-1">
        <firmware name="node_9.jtag.s3"/>
        <phy x="845" y="568" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <parameter value="NO_DEMOBOARD" name="HW_MODALITY"/>
        <parameter value="-96" name="M_FREQ_OFFSET"/>
        <sensors/>
    </node>
    <node target="aps3" simulation="false" id="2" area="1" name="node pir 2-1">
        <firmware name="node_2.jtag.s3"/>
        <phy x="783" y="766" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="762" y="787" z_rotation="155"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="aps3" simulation="false" id="3" area="1" name="node pir 3-1">
        <firmware name="node_3.jtag.s3"/>
        <phy x="925" y="712" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="905" y="738" z_rotation="160"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <!-- Zone 2-->
    <node target="host" simulation="true" id="1" area="2" name="node root reasoning 2">
        <emblem source="c2.png"/>
        <firmware name="node_1"/>
        <phy x="1065" y="822" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl prefix="1180:0000:0000:0000">
            <restrict_neighbors>
                <neighbor node_id="20"/>
                <neighbor node_id="2"/>
                <neighbor node_id="3"/>
                <neighbor node_id="4"/>
                <neighbor node_id="21"/>
                <neighbor node_id="22"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true" broker="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <gateway port="1235"/>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5">
            <!-- This node is the reasoning node -->
            <reasoning_node log_analyse_period="1440"/>
            <!-- in minutes -->
            <monitored_area area="1" average_crossing_duration="20"/>
        </reasoning>
        <sensors/>
    </node>
    <node target="aps3" simulation="false" id="21" area="2" name="node pir 1-2">
        <firmware name="node_21.jtag.s3"/>
        <phy x="1174" y="632" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <parameter value="NO_DEMOBOARD" name="HW_MODALITY"/>
        <parameter value="-240" name="M_FREQ_OFFSET"/>
        <sensors>
            <modality type="SEISMIC">
                <sensor period="200" reemission_delay="5001" type="digital" id="0" delay="0">
                    <gpio pin="3"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="1121" y="614" z_rotation="80"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="aps3" simulation="false" id="22" area="2" name="node pir 2-2">
        <firmware name="node_22.jtag.s3"/>
        <phy x="1294" y="567" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="white" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <parameter value="WITH_SPIRIT" name="HW_MODALITY"/>
        <parameter value="-240" name="M_FREQ_OFFSET"/>
        <sensors>
            <modality type="SPIRIT">
                <sensor period="500" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="0"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="1240" y="584" z_rotation="190"/>
                </sensor>
            </modality>
        </sensors>
    </node>
</network>

=== mupuf/diaforus_labri/diaforus/scenarios/ferte/ferte_mobile_C2_net_toMobileC2.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE network SYSTEM '../network.dtd'>
<network failure_handling="false" pubsub_reliable="true">
    <build>
        <!--	path: filepath to the make binary (optional)
			args: parameters you can specify for make (optional)
			root: the directory that contains the Makefile
			output: the binary file generated by the project
		-->
        <make output="diaforus_final_code" root="Default/" target="host" args="-j8"/>
        <make output="diaforus_final_code.jtag.s3" root="Debug/" target="aps3" args="-j1"/>
        <debug pubsub="true" uip="true" sicslowpan="true" rpl="true" wavesim="true" coap="truz" reasoning="true"/>
        <application name="REASONING"/>
    </build>
    <coap_groups>
        <group name="reasoning1">
            <resource name="intrusion_duration"/>
            <resource name="latency_mode"/>
        </group>
        <group name="reasoning2">
            <resource name="hist_analyze_per"/>
            <resource name="criticality_lvl"/>
            <resource name="history"/>
            <resource name="alert_alarm_ratio"/>
        </group>
        <group name="rpl">
            <resource name="rpl_neighbors"/>
            <resource name="rpl_rank"/>
            <resource name="rpl_num_routes"/>
            <resource name="rpl_num_tra_mess"/>
            <resource name="rpl_num_rec_mess"/>
        </group>
        <group name="allnodes">
            <resource name="num_tra_packets"/>
            <resource name="num_rec_packets"/>
            <resource name="nodeid"/>
        </group>
    </coap_groups>
    <!-- Zone 1 -->
    <node target="host" simulation="false" id="20" area="1" name="node root reasoning 1">
        <firmware name="node_20"/>
        <phy x="910" y="865" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
                <neighbor node_id="2"/>
                <neighbor node_id="3"/>
                <neighbor node_id="4"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="green" max_intrusion_duration="10" min_intrusion_duration="5">
            <!-- This node is the reasoning node -->
            <reasoning_node log_analyse_period="1440"/>
        </reasoning>
        <sensors/>
    </node>
    <node target="aps3" simulation="false" id="2" area="1" name="node pir 2-1">
        <firmware name="node_2.jtag.s3"/>
        <phy x="786" y="856" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="738" y="798" z_rotation="-110"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="aps3" simulation="false" id="5" area="1" name="node pir 2-1">
        <firmware name="node_5.jtag.s3"/>
        <phy x="846" y="743" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <parameter value="-136" name="M_FREQ_OFFSET"/>
        <reasoning latency_mode="green" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <sensors>
            <modality type="SEISMIC">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="819" y="719" z_rotation="155"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="aps3" simulation="false" id="3" area="1" name="node pir 3-1">
        <firmware name="node_3.jtag.s3"/>
        <phy x="956" y="799" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
            <restrict_neighbors>
                <neighbor node_id="1"/>
            </restrict_neighbors>
        </rpl>
        <pubsub enable="true"/>
        <coap enable="true">
            <group name="reasoning1"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <reasoning latency_mode="green" max_intrusion_duration="10" min_intrusion_duration="5"/>
        <sensors>
            <modality type="PIR">
                <sensor period="200" reemission_delay="3001" type="digital" id="0" delay="0">
                    <gpio pin="2"/>
                    <value abs_threshold="1" rel_threshold="1" invert="false"/>
                    <position x="905" y="738" z_rotation="-110"/>
                </sensor>
            </modality>
        </sensors>
    </node>
    <node target="host" simulation="true" id="9" area="1" name="mobile C2">
        <emblem source="c2.png"/>
        <firmware name="node_9"/>
        <phy x="629" y="616" range="900"/>
        <energy startup="1600" alarm="100"/>
        <rpl>
        	<restrict_neighbors>
				<neighbor node_id="2" />
			</restrict_neighbors>
		</rpl> 
        <pubsub enable="false" broker="true"/>
        <coap enable="true">
            <group name="reasoning2"/>
            <group name="rpl"/>
            <group name="allnodes"/>
        </coap>
        <gateway port="1235"/>
        <!-- The parameters to control the reasoning (level 1 and level 2) -->
        <reasoning latency_mode="orange" max_intrusion_duration="20" min_intrusion_duration="2"/>
         <parameter name="INDOOR_SCENARIO" value="1" />
         <parameter name="MOBILE_C2" value="1" />
        <sensors/>
    </node>
</network>
